### ISSUE TITLE
Frozen strings

### ISSUE THREAD

**Issue by cutalion** [undr/cloud_payments#8]
Would you accept PR which passes [Frozen String Literal cop](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment) from rubocop?

It would be help to upgrade to ruby 3.0.

**Comment by undr** [comment]
@cutalion Yes, I would. But I hope it will not break support of versions prior 2.3, will it?

**Comment by cutalion** [comment]
@undr when will you release new version? I don't want to specify master branch in Gemfile.

**Comment by undr** [comment]
@cutalion I'll it soon.

**Comment by undr** [comment]
@cutalion done
